spring:
  application:
    name: admin-server
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        location: http://127.0.0.1:8989

eureka:
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: admin-server
      clientSecret: '1234'
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      userAuthorizationUri: http://localhost:5000/uaa/oauth/authorize
      #grant-type: client_credentials
      scope: openid
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current

server:
  context-path: /
  port: 8764
  
logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG