spring:
    application:
        name: admin-server
    boot:
        admin:
            routes:
                endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
            turbine:
                location: http://127.0.0.1:8989
server:
    port: 8764
security:
    user:
        name: whb
        password: 123456
        role: USER
eureka:
    instance:
        preferIpAddress: true
        ip-address: 127.0.0.1
    client:
        registerWithEureka: false
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/