version: '2'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000
      
  auth-redis:
    build: redis
    ports:
      - 6379:6379

#  auth-mongodb:
#    build: mongodb
#    ports:
#      - 25000:27017

  account-service:
    build: account-service
    ports:
      - 6100:6100

#  account-mongodb:
#    build: mongodb
#    ports:
#      - 26000:27017

#  statistics-service:
#    build: statistics-service
#    ports:
#      - 7000:7000
#
#  statistics-mongodb:
#    build: mongodb
#    ports:
#      - 27000:27017
#
#  notification-service:
#    build: notification-service
#    ports:
#      - 8000:8000
#
#  notification-mongodb:
#    build: mongodb
#    ports:
#      - 28000:27017

  monitoring:
    build: monitoring
    
  admin-server:
    build: admin-service
    ports:
      - 8764:8764