spring:   
  redis:
    cluster:
      nodes:
      - 127.0.0.1:6379
      - 127.0.0.1:6380
      - 127.0.0.1:6381
      max-redirects: 6

server:
  context-path: /uaa
  port: 5000

swagger2:
  title: 授权服务（Auth）
  description: Spring Cloud 微服务平台 - 授权服务
  termsOfServiceUrl: https://github.com/sniperqpc
  contact:
    name: Roc Chiu
    url: https://github.com/sniperqpc
    email: 353386051@qq.com
  version: V1.0